<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Central Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.52" os="Windows 7" host="LOCALHOST"><DocLocation><![CDATA[C:\SampleQtpUftRunResultsTest]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[SampleQtpUftRunResultsTest]]></DName>
<Res><![CDATA[Res2]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[12/5/2016 - 11:35:27]]></Time>
<TimeTick>1480959327</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Zero - Personal Banking]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/5/2016 - 11:35:27]]></Time>
<TimeTick>1480959327</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Zero - Personal Banking.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/5/2016 - 11:35:27]]></Time>
<TimeTick>1480959327</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Zero - Personal Banking.Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="11" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Zero - Personal Banking]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Browser.Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to http://zero.webappsecurity.com/index.html<br>Target Frame: _top<br>Post Data: <br>HTTP Headers: ]]></Details>
<Time><![CDATA[12/5/2016 - 11:35:27]]></Time>
<TimeTick>1480959327</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="14" Source="Action1" SourceLine="2" >
<Disp><![CDATA[Browser.Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Zero - Personal Banking]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/5/2016 - 11:35:28]]></Time>
<TimeTick>1480959328</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Feedback.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/5/2016 - 11:35:28]]></Time>
<TimeTick>1480959328</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="18" Source="Action1" SourceLine="3" >
<Disp><![CDATA[Feedback.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf20.xml]]></Path>
<ASHilite><![CDATA[Browser("Browser").Page("Zero - Personal Banking").WebElement("Feedback")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="17" Source="Action1" SourceLine="3" >
<Disp><![CDATA[Zero - Personal Banking]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf19.xml]]></Path>
<ASHilite><![CDATA[Browser("Browser").Page("Zero - Personal Banking")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Zero - Contact Us]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/5/2016 - 11:35:30]]></Time>
<TimeTick>1480959330</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[comment.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hello"]]></Details>
<Time><![CDATA[12/5/2016 - 11:35:30]]></Time>
<TimeTick>1480959330</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="22" Source="Action1" SourceLine="4" >
<Disp><![CDATA[comment.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf22.xml]]></Path>
<ASHilite><![CDATA[Browser("Browser").Page("Zero - Contact Us").WebEdit("comment")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Send Message.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/5/2016 - 11:35:30]]></Time>
<TimeTick>1480959330</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="25" Source="Action1" SourceLine="5" >
<Disp><![CDATA[Send Message.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf23.xml]]></Path>
<ASHilite><![CDATA[Browser("Browser").Page("Zero - Contact Us").WebButton("Send Message")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Zero Bank.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/5/2016 - 11:35:30]]></Time>
<TimeTick>1480959330</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="28" Source="Action1" SourceLine="6" >
<Disp><![CDATA[Zero Bank.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf24.xml]]></Path>
<ASHilite><![CDATA[Browser("Browser").Page("Zero - Contact Us").Link("Zero Bank")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="21" Source="Action1" SourceLine="4" >
<Disp><![CDATA[Zero - Contact Us]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf21.xml]]></Path>
<ASHilite><![CDATA[Browser("Browser").Page("Zero - Contact Us")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="10" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Browser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj ><![CDATA[pass step]]></Obj>
<Details ><![CDATA[description]]></Details>
<Time><![CDATA[12/5/2016 - 11:35:30]]></Time>
<TimeTick>1480959330</TimeTick>
<NodeArgs eType="User" icon="11" nRep="29" status="Passed" Source="Action1" SourceLine="7" >
<Disp><![CDATA[pass step]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="12/5/2016 - 11:35:27" eTime="12/5/2016 - 11:35:30" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[SampleQtpUftRunResultsTest Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T16" iterID="2" >
<Action rID="T17">
<AName><![CDATA[Action1]]></AName>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[12/5/2016 - 11:35:31]]></Time>
<TimeTick>1480959331</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Zero - Personal Banking]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/5/2016 - 11:35:31]]></Time>
<TimeTick>1480959331</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Zero - Personal Banking.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/5/2016 - 11:35:31]]></Time>
<TimeTick>1480959331</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="38" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Zero - Personal Banking.Sync]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf26.xml]]></Path>
<ASHilite><![CDATA[Browser("Browser").Page("Zero - Personal Banking")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="37" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Zero - Personal Banking]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf25.xml]]></Path>
<ASHilite><![CDATA[Browser("Browser").Page("Zero - Personal Banking")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Browser.Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to http://zero.webappsecurity.com/index.html<br>Target Frame: _top<br>Post Data: <br>HTTP Headers: ]]></Details>
<Time><![CDATA[12/5/2016 - 11:35:31]]></Time>
<TimeTick>1480959331</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="40" Source="Action1" SourceLine="2" >
<Disp><![CDATA[Browser.Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Zero - Personal Banking]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/5/2016 - 11:35:32]]></Time>
<TimeTick>1480959332</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Feedback.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/5/2016 - 11:35:32]]></Time>
<TimeTick>1480959332</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="44" Source="Action1" SourceLine="3" >
<Disp><![CDATA[Feedback.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf28.xml]]></Path>
<ASHilite><![CDATA[Browser("Browser").Page("Zero - Personal Banking").WebElement("Feedback")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="43" Source="Action1" SourceLine="3" >
<Disp><![CDATA[Zero - Personal Banking]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf27.xml]]></Path>
<ASHilite><![CDATA[Browser("Browser").Page("Zero - Personal Banking")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Zero - Contact Us]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/5/2016 - 11:35:33]]></Time>
<TimeTick>1480959333</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[comment.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hello"]]></Details>
<Time><![CDATA[12/5/2016 - 11:35:33]]></Time>
<TimeTick>1480959333</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="48" Source="Action1" SourceLine="4" >
<Disp><![CDATA[comment.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf30.xml]]></Path>
<ASHilite><![CDATA[Browser("Browser").Page("Zero - Contact Us").WebEdit("comment")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Send Message.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/5/2016 - 11:35:33]]></Time>
<TimeTick>1480959333</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="51" Source="Action1" SourceLine="5" >
<Disp><![CDATA[Send Message.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf31.xml]]></Path>
<ASHilite><![CDATA[Browser("Browser").Page("Zero - Contact Us").WebButton("Send Message")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Zero Bank.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/5/2016 - 11:35:33]]></Time>
<TimeTick>1480959333</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="54" Source="Action1" SourceLine="6" >
<Disp><![CDATA[Zero Bank.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf32.xml]]></Path>
<ASHilite><![CDATA[Browser("Browser").Page("Zero - Contact Us").Link("Zero Bank")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="47" Source="Action1" SourceLine="4" >
<Disp><![CDATA[Zero - Contact Us]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf29.xml]]></Path>
<ASHilite><![CDATA[Browser("Browser").Page("Zero - Contact Us")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="36" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Browser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj ><![CDATA[pass step]]></Obj>
<Details ><![CDATA[description]]></Details>
<Time><![CDATA[12/5/2016 - 11:35:33]]></Time>
<TimeTick>1480959333</TimeTick>
<NodeArgs eType="User" icon="11" nRep="55" status="Passed" Source="Action1" SourceLine="7" >
<Disp><![CDATA[pass step]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj ><![CDATA[fail step]]></Obj>
<Details ><![CDATA[description]]></Details>
<Time><![CDATA[12/5/2016 - 11:35:33]]></Time>
<TimeTick>1480959333</TimeTick>
<NodeArgs eType="User" icon="11" nRep="56" status="Failed" Source="Action1" SourceLine="9" >
<Disp><![CDATA[fail step]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="12/5/2016 - 11:35:30" eTime="12/5/2016 - 11:35:33" passed="1" failed="1" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="33" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="32" status="Failed" >
<Disp><![CDATA[SampleQtpUftRunResultsTest Iteration 2 (Row 2)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="12/5/2016 - 11:35:26" eTime="12/5/2016 - 11:35:33" passed="2" failed="1" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test SampleQtpUftRunResultsTest Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>